### ISSUE TITLE
Error when trying to discover the blogger:v3 API

### ISSUE THREAD

**Issue by Konstantinusz** [tokland/shoogle#12]
When I issue this command: "shoogle show blogger:v3.posts.list"
Then I get an error message:

```
Traceback (most recent call last):
  File "/usr/bin/shoogle", line 12, in <module>
    sys.exit(shoogle.main(sys.argv[1:]))
  File "/home/walaki/.local/lib/python3.8/site-packages/shoogle/shoogle.py", line 52, in main
    return run(args)
  File "/home/walaki/.local/lib/python3.8/site-packages/shoogle/shoogle.py", line 39, in run
    commands.show.run(options)
  File "/home/walaki/.local/lib/python3.8/site-packages/shoogle/commands/show.py", line 26, in run
    show_methods(service_id, resource_name, method_name, options)
  File "/home/walaki/.local/lib/python3.8/site-packages/shoogle/commands/show.py", line 79, in show_methods
    show_method(service, methods[search_method_name], options)
  File "/home/walaki/.local/lib/python3.8/site-packages/shoogle/commands/show.py", line 125, in show_method
    request = get_example_request(minimal_params, schemas, level)
  File "/home/walaki/.local/lib/python3.8/site-packages/shoogle/commands/show.py", line 96, in get_example_request
    description = re.sub("\.\s*$", "", opts["description"].splitlines()[0])
KeyError: 'description'

```

**Comment by davesteele** [comment]
I'm getting the same response.
