### ISSUE TITLE
ImportError: No module named 'pypandoc'

### ISSUE THREAD

**Issue by tlvince** [tokland/shoogle#3]
I'm getting the following on install:

```
❯ pip3 install --user shoogle
Collecting shoogle
  Downloading shoogle-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/_n/vc1rw4250cbb96q5pfkflndw0000gn/T/pip-build-a6jqpgoh/shoogle/setup.py", line 3, in <module>
        import pypandoc
    ImportError: No module named 'pypandoc'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_n/vc1rw4250cbb96q5pfkflndw0000gn/T/pip-build-a6jqpgoh/shoogle
```

Same thing happens with `sudo` or `pip2`.

**Comment by tokland** [comment]
Install `pypandoc`first.
